# -*- coding: utf-8 -*-
"""day17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-rgsn3LvBukTRtWBCXTmcUusFc8GB1pR
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from statsmodels.stats.multicomp import pairwise_tukeyhsd

tips = sns.load_dataset("tips")

print("First 5 rows:")
print(tips.head())

print("\nInfo:")
print(tips.info())

print("\nShape:", tips.shape)
print("\nColumns:", tips.columns)

print("\nDescriptive Statistics:")
print(tips.describe(include='all'))

# Missing values %
missing_percent = (tips.isnull().sum().sum() / tips.size) * 100
print("\nMissing Value %:", missing_percent)

print("\nSex count:")
print(tips['sex'].value_counts())

print("\nTime count:")
print(tips['time'].value_counts())

plt.figure(figsize=(6,4))
sns.barplot(x='sex', y='tip', data=tips, estimator='mean')
plt.title("Average Tip by Sex")
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(data=tips, x='tip', hue='sex', kde=True)
plt.title("Tip Distribution by Sex")
plt.show()

plt.figure(figsize=(6,4))
sns.barplot(x='time', y='tip', data=tips, estimator='mean')
plt.title("Average Tip by Time")
plt.show()

plt.figure(figsize=(6,4))
sns.histplot(data=tips, x='tip', hue='time', kde=True)
plt.title("Tip Distribution by Time")
plt.show()

dinner_tip = tips[tips['time'] == 'Dinner']['tip']
lunch_tip = tips[tips['time'] == 'Lunch']['tip']

t_stat, p_val = stats.ttest_ind(dinner_tip, lunch_tip)

print("T-Statistic:", t_stat)
print("P-Value:", p_val)

alpha = 0.05
if p_val < alpha:
    print("Reject H0 → Dinner and Lunch tips differ")
else:
    print("Fail to Reject H0")

df = sns.load_dataset("taxis")

print(df.head())
print(df.info())
print(df.describe(include='all'))

credit_tip = df[df['payment'] == 'credit card']['tip']
cash_tip = df[df['payment'] == 'cash']['tip']

t_stat, p_val = stats.ttest_ind(credit_tip, cash_tip, nan_policy='omit')

print("T-Statistic:", t_stat)
print("P-Value:", p_val)

if p_val < alpha:
    print("Reject H0 → Tips differ by payment method")
else:
    print("Fail to Reject H0")

df_tukey = df[['tip', 'pickup_borough']].dropna()

tukey = pairwise_tukeyhsd(
    endog=df_tukey['tip'],
    groups=df_tukey['pickup_borough'],
    alpha=0.05
)

print(tukey)

plt.figure(figsize=(10,4))
sns.barplot(x='pickup_borough', y='tip', data=df, estimator='std')
plt.title("Tip Variability by Pickup Borough")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,4))
sns.histplot(data=df, x='tip', hue='pickup_borough', kde=True)
plt.title("Tip Distribution by Pickup Borough")
plt.show()

pickup_groups = [g['tip'].dropna().values for _, g in df.groupby('pickup_zone')]
f_stat, p_val = stats.f_oneway(*pickup_groups)

print("ANOVA Pickup Zone")
print("F:", f_stat, "P:", p_val)

dropoff_groups = [g['tip'].dropna().values for _, g in df.groupby('dropoff_zone')]
f_stat, p_val = stats.f_oneway(*dropoff_groups)

print("\nANOVA Dropoff Zone")
print("F:", f_stat, "P:", p_val)

print("\nINSIGHTS:")
print("✔ Tips differ by time (Lunch vs Dinner)")
print("✔ Payment method affects tips")
print("✔ Pickup borough & zones influence tip amounts")
print("✔ ANOVA confirms location impact on tipping behavior")
