# -*- coding: utf-8 -*-
"""day17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-rgsn3LvBukTRtWBCXTmcUusFc8GB1pR
"""

import seaborn as sns
import pandas as pd

# Load tips dataset
tips = sns.load_dataset("tips")

# View first 5 rows
tips.head()

import seaborn as sns
import pandas as pd

# Load tips dataset
tips = sns.load_dataset("taxis")

# View first 5 rows
tips.head()

tips.info()

tips.columns

tips.shape

tips.describe(include='all')

# Import libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the tips dataset
df = sns.load_dataset("tips")  # correct dataset name

# Display first 5 rows
print("First 5 rows:")
print(df.head())

# Dataset info
print("\nDataset info:")
print(df.info())

# Shape of the dataset
print("\nShape of dataset:", df.shape)

# Column names
print("\nColumns:", df.columns)

# Descriptive statistics
print("\nDescriptive statistics:")
print(df.describe(include='all'))

# Percentage of missing values
missing_percent = ((df.shape[0] - df.dropna().shape[0]) / df.shape[0]) * 100
print("\nPercentage of missing values:", missing_percent)

# Value counts for 'sex' column (since 'color' doesn't exist)
print("\nValue counts for 'sex':")
print(df['sex'].value_counts())

# Barplot of average tip by sex
plt.figure(figsize=(6,4))
sns.barplot(x='sex', y='tip', data=df, estimator='mean')
plt.title("Average Tip by Sex")
plt.show()

# Histogram of tip by sex with KDE
plt.figure(figsize=(6,4))
sns.histplot(x='tip', hue='sex', data=df, kde=True, palette={'Male':'green','Female':'yellow'})
plt.title("Tip Distribution by Sex")
plt.show()

import seaborn as sns
from scipy import stats

# Load taxis dataset
df = sns.load_dataset('taxis')

# Separate tip amounts by payment method
credit_tip = df.loc[df['payment'] == 'credit card', 'tip']
cash_tip = df.loc[df['payment'] == 'cash', 'tip']

# Independent T-Test
t_stat, p_val = stats.ttest_ind(credit_tip, cash_tip)

print("Independent T-Test statistic:", t_stat)
print("P-value:", p_val)

alpha = 0.05  # significance level

if p_val < alpha:
    print("Reject null hypothesis: The tip for credit card payment is different from cash")
else:
    print("Fail to reject null hypothesis")

import seaborn as sns
import matplotlib.pyplot as plt

tips = sns.load_dataset("tips")

sns.histplot(x=tips.tip, hue=tips.sex, kde=True, palette=['green', 'yellow'])
plt.show()

# Check counts of hue
print(tips.sex.value_counts())

import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

# Load the tips dataset
tips = sns.load_dataset("tips")

# Barplot: Time vs Tip
sns.barplot(x='time', y='tip', data=tips, estimator='mean')
plt.title("Average Tip by Time")
plt.show()

# Histogram with hue
sns.histplot(x='tip', hue='time', data=tips, kde=True, palette=['green', 'yellow'])
plt.title("Tip Distribution by Time")
plt.show()

# Independent T-Test: Dinner vs Lunch tips
dinner_tip = tips['tip'][tips['time'] == 'Dinner']
lunch_tip = tips['tip'][tips['time'] == 'Lunch']

t_stat, p_val = stats.ttest_ind(dinner_tip, lunch_tip)
print("Independent T-Test statistic:", t_stat)
print("p-value:", p_val)

alpha = 0.05
if p_val < alpha:
    print("Reject null hypothesis: The tip for Dinner is different from Lunch")
else:
    print("Fail to reject null hypothesis")

import pandas as pd
from statsmodels.stats.multicomp import pairwise_tukeyhsd

df_tukey = df[['tip', 'pickup_borough']].copy()

# Force correct types
df_tukey['tip'] = pd.to_numeric(df_tukey['tip'], errors='coerce')
df_tukey['pickup_borough'] = df_tukey['pickup_borough'].astype(str)

# Remove invalid rows
df_tukey = df_tukey.dropna()

# Remove empty strings if any
df_tukey = df_tukey[df_tukey['pickup_borough'].str.strip() != ""]

# Reset index
df_tukey.reset_index(drop=True, inplace=True)

# Tukey test
tukey = pairwise_tukeyhsd(
    endog=df_tukey['tip'].values,
    groups=df_tukey['pickup_borough'].values,
    alpha=0.05
)

print(tukey)

import pandas as pd
from statsmodels.stats.multicomp import pairwise_tukeyhsd

df_tukey = df[['tip', 'pickup_borough']].copy()

# Force correct types
df_tukey['tip'] = pd.to_numeric(df_tukey['tip'], errors='coerce')
df_tukey['pickup_borough'] = df_tukey['pickup_borough'].astype(str)

# Remove invalid rows
df_tukey = df_tukey.dropna()

# Remove empty strings if any
df_tukey = df_tukey[df_tukey['pickup_borough'].str.strip() != ""]

# Reset index
df_tukey.reset_index(drop=True, inplace=True)

# Tukey test
tukey = pairwise_tukeyhsd(
    endog=df_tukey['tip'].values,
    groups=df_tukey['pickup_borough'].values,
    alpha=0.05
)
print(tukey)

sns.barplot(x=df['pickup_borough'],y=df['tip'],palette='Set2',estimator='std')

sns.histplot(x=df['tip'],hue=df['pickup_borough'],bins=20,kde=True,palette='Set2')

import pandas as pd
from scipy import stats

# Assuming df is your DataFrame
# df = pd.read_csv("your_file.csv")  # Uncomment if reading from CSV

# ----------------------------
# ANOVA Test for pickup_zone
# ----------------------------
pickup_categories = [group['tip'].values for name, group in df.groupby('pickup_zone')]
f_stat_pickup, p_val_pickup = stats.f_oneway(*pickup_categories)

print("ANOVA Test for pickup_zone")
print(f"F-Statistic: {f_stat_pickup}")
print(f"P-Value: {p_val_pickup}")

alpha = 0.05
if p_val_pickup < alpha:
    print("Reject Null Hypothesis: At least one pickup_zone group differs in tip.")
else:
    print("Fail to reject Null Hypothesis: All pickup_zone groups have similar tip distribution.")

# ----------------------------
# ANOVA Test for dropoff_zone
# ----------------------------
dropoff_categories = [group['tip'].values for name, group in df.groupby('dropoff_zone')]
f_stat_dropoff, p_val_dropoff = stats.f_oneway(*dropoff_categories)

print("\nANOVA Test for dropoff_zone")
print(f"F-Statistic: {f_stat_dropoff}")
print(f"P-Value: {p_val_dropoff}")

if p_val_dropoff < alpha:
    print("Reject Null Hypothesis: At least one dropoff_zone group differs in tip.")
else:
    print("Fail to reject Null Hypothesis: All dropoff_zone groups have similar tip distribution.")

# ----------------------------
# Insights and Decision
# ----------------------------
print("\nInsights:")
if p_val_pickup < alpha and p_val_dropoff < alpha:
    print("Both pickup_zone and dropoff_zone have a statistically significant effect on tip.")
elif p_val_pickup < alpha:
    print("Only pickup_zone has a statistically significant effect on tip.")
elif p_val_dropoff < alpha:
    print("Only dropoff_zone has a statistically significant effect on tip.")
else:
    print("Neither pickup_zone nor dropoff_zone significantly affects tip.")